name: 'ktlibs-${name}'
version: '${version}'
main: io.coplt.mcplg.ktlibs.kotlinx_datetime.BukkitEntryPoint
load: STARTUP
author: kotlin-libs-mcplg
depend:
  - 'ktlibs-kotlin-stdlib'
  - 'ktlibs-kotlinx-serialization'
