name: 'ktlibs-${name}'
version: '${version}'
api-version: 1.13
main: io.coplt.mcplg.ktlibs.ktorm.BukkitEntryPoint
load: STARTUP
author: kotlin-libs-mcplg
depend:
  - 'ktlibs-kotlin-stdlib'
  - 'ktlibs-kotlin-reflect'
