name: Check versions

on:
  #schedule:
  #  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Do Check
        run: 'deno task check'
        env:
          input_github_actions: ${{ github.action }}
          input_github_token: ${{ github.token }}
          input_github_repository: ${{ github.repository }}
          input_github_repository_owner: ${{ github.repository_owner }}
