name: Check versions

on:
  #schedule:
  #  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Do Check
        run: 'deno task check'
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
