name: Check versions

on:
  #schedule:
  #  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      versions_change: ${{ steps.check.outputs.versions_change }}
      branch_name: ${{ steps.check.outputs.branch_name }}
      commit_msg: ${{ steps.check.outputs.commit_msg }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - id: check
        name: Do Check
        run: "deno task check"
        env:
          GITHUB_ACTION: ${{ github.action }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

  build:
    runs-on: ubuntu-latest

    needs: check
    if: needs.check.outputs.versions_change

    steps:
      - env:
          BRANCH_NAME: ${{ needs.check.outputs.branch_name }}
        run: echo "$BRANCH_NAME"

      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.check.outputs.branch_name }}

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

  merge:
    runs-on: ubuntu-latest

    needs: [check, build]

    outputs:
      commit_sha: ${{ steps.merge.outputs.commit_sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - id: merge
        name: Do Merge
        run: "deno task merge"
        env:
          GITHUB_ACTION: ${{ github.action }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          BRANCH_NAME: ${{ needs.check.outputs.branch_name }}
          COMMIT_MSG: ${{ needs.check.outputs.commit_msg }}

  diff_versions:
    runs-on: ubuntu-latest

    needs: [merge]

    steps:
      - uses: ./.github/workflows/diff
        secrets:
          modrinth-token: ${{ secrets.MODRINTH }}
        with:
          commit-ref: ${{ needs.merge.outputs.commit_sha }}
