name: Deploy to modrinth

on:
  workflow_call:
    secrets:
      modrinth-token:
        required: true
    inputs:
      commit-ref:
        type: string
        default: "main"
        required: true
      item:
        type: string
        default: "kotlin-stdlib:1.9.10"
        required: true

  workflow_dispatch:
    inputs:
      commit-ref:
        type: string
        default: "main"
        required: true
      item:
        type: string
        default: "kotlin-stdlib:1.9.10"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      artifact_name: ${{ steps.deploy_build.outputs.artifact_name }}
      artifact_path: ${{ steps.deploy_build.outputs.artifact_path }}

    steps:
      - env:
          COMMIT_REF: ${{ inputs.commit-ref }}
          PROJECT_AND_VERSION: ${{ inputs.item }}
        run: echo "$COMMIT_REF ; $PROJECT_AND_VERSION"

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-ref }}

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - id: ready_deploy
        name: Ready deploy
        run: "deno task ready_deploy"
        env:
          PROJECT_AND_VERSION: ${{ inputs.item }}

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - id: deploy_build
        name: Deploy build
        run: "deno task deploy_build"
        env:
          PROJECT_AND_VERSION: ${{ inputs.item }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.deploy_build.outputs.artifact_name }}
          path: ${{ steps.deploy_build.outputs.artifact_path }}
